### ISSUE TITLE
Correct locations

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [Phanx/HandyNotes_HigherLearning#1]
Divination: 26.47, 52.20
Transmutation: 46.81, 40.04

Necromancy is actually exactly where you currently have Transmutation. I havent picked up Transmutation on this character yet so I cant tell if you have them on top of eachother or you just dont have Necromancy in.

Introduction: Correct
Illusion: Correct
Enchantment: Correct
Abjuration: Correct
Conjuration: Correct

**Comment by F-I-R-E-F-O-X** [comment]
You also probably want to put a note in there saying what floor they're on since there are multiple levels / severs with the same coords as well.

**Comment by Phanx** [comment]
Necromancy and Transmutation are very close to each other on the map (if you're zoomed out they might appear to be in the same place) but Necromancy is upstairs and Transmutation is downstairs.

Notes are a good idea, I'll add some.

_Edit:_ Notes added in version 6.2.0.4. Also adjusted the coordinates for Divination and Transmuation, not sure why they were slightly off in the first place.
