### ISSUE TITLE
attempt to call global 'GetCurrentMapAreaID' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [Phanx/HandyNotes_HigherLearning#3]
Receiving the following error after updating to 8.0.

Date: 2018-07-18 22:18:27
ID: 12
Error occured in: Global
Count: 3
Message: ..\AddOns\HandyNotes_HigherLearning\Addon.lua line 166:
   attempt to call global 'GetCurrentMapAreaID' (a nil value)
Debug:
   (tail call): ?
   [C]: GetCurrentMapAreaID()
   HandyNotes_HigherLearning\Addon.lua:166:
      HandyNotes_HigherLearning\Addon.lua:164
   (tail call): ?
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:

Thanks.

**Comment by Phanx** [comment]
Fixed
