### ISSUE TITLE
Bug for Patch 8.0.1 

### ISSUE THREAD

**Issue by chelpixie** [Phanx/HandyNotes_HigherLearning#4]
Message: Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:166: attempt to call global 'GetCurrentMapAreaID' (a nil value)
Time: Thu Jul 19 16:42:09 2018
Count: 1
Stack: Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:166: attempt to call global 'GetCurrentMapAreaID' (a nil value)
Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:166: in function <Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:164>
(tail call): ?

Locals: self = <unnamed> {
 PLAYER_LOGIN = <function> defined @Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:157
 CRITERIA_COMPLETE = <function> defined @Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:173
 0 = <userdata>
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\HandyNotes_HigherLearning\Addon.lua:164
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetCurrentMapAreaID' (a nil value)"

**Comment by Scaver** [comment]
I get the same error.

**Comment by Diijakr** [comment]
Same here!

**Comment by Phanx** [comment]
Fixed
