### ISSUE TITLE
Get Current Map Area ID

### ISSUE THREAD

**Issue by Mardleseyth** [Phanx/HandyNotes_HigherLearning#5]
19x HandyNotes_HigherLearning\Addon.lua:166: attempt to call global 'GetCurrentMapAreaID' (a nil value)
HandyNotes_HigherLearning\Addon.lua:166: in function <HandyNotes_HigherLearning\Addon.lua:164>
(tail call): ?

Locals:
self = <unnamed> {
PLAYER_LOGIN = <function> defined @HandyNotes_HigherLearning\Addon.lua:157
CRITERIA_COMPLETE = <function> defined @HandyNotes_HigherLearning\Addon.lua:173
0 = <userdata>
ZONE_CHANGED_NEW_AREA = <function> defined @HandyNotes_HigherLearning\Addon.lua:164
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetCurrentMapAreaID' (a nil value)"

**Comment by Phanx** [comment]
Please make sure you have the latest version of an addon (or any software) before reporting a bug. You are using an old version of the addon that is not compatible with the current version of WoW. The current version of the addon was published on July 29th, over 2 weeks before the date of your report.
